### ISSUE TITLE
Rework specialities

### ISSUE THREAD

**Issue by johannes-z** [ehrpg/books#10]
### Problem:

While a skill of 10 is very hard to reach, specialities make it very easy to get a bonus of 10 very early in the game. The soldier background f.e. may have +6 on rifles, making combat very unbalanced.

---

Specialities could be changed altogether to create a basic set of perks, while perks themselves could be categorised. F.e., some perks can only be acquired after a certain deed in-game (such as successfully flying a military space ship, have a high enough kill counter with a certain weapon), while other more basic perks can be acquired after reaching a certain skill level. F.e., the speciality "Rifles" for the skill "small arms" could be a perk, that allows to the character to "instantly" reload his weapon, without having to use an action on it, or that he may use the "take aim" action as a free action.

**Comment by n0la** [comment]
Specialities have been removed. So I guess this issue can be closed?
