### ISSUE TITLE
Rework combat

### ISSUE THREAD

**Issue by johannes-z** [ehrpg/books#11]
### Problem:

Combat is too deadly right now, especially on longer range engagements. The penalties from range are easily countered by high skill ranks (see #10), or the aim action. AP ammunition is pretty cheap too, so having a magazine of AP ammo can easily be assumed, making almost all types of armour inefficient. It's also difficult to discern, when a character sees another character. If f.e. a sniper is lying somewhere, he mustn't be necessarily be hiding, but simply too far away to really notice him with the naked eye. 
### Conclusion:
1. Combat modifiers such as walking, lying, etc. should have more impact the further the range. Also, longer range engagements should be made harder - the difficulty here seems to be the range finding (see https://en.wikipedia.org/wiki/Craig_Harrison_(sniper)), and some kind of requirement of a spotter, or a penalty if nobody is filling this position.
   - Self-movement should be much more penalising at longer range. Playtest#2 (see #9) showed, that it was very easy to hit a target at 100-200 metres with an assault rifle while moving, shooting at a on the ground lying enemy.
2. Taking cover on longer range should be much more effective. If f.e. a sniper shoots at someone in a group of trees, the enemies could easily hide behind trees, making it for the sniper, who only has a very restricted peripheral vision, almost impossible to discern behind which tree they are hiding.
3. Target zones are extremely unbalanced right now. Vital organs should only be hit on a critical hit (either a 10, but a major effect would suit better... this creates the problem though, that a character could want to shoot at a specific target zone, including the vital organs). 
4. Bullets should do less damage, unless they create a wound. The bullet itself should only do a minimal, dynamic damage that is determined by dice (fewer and less sides than now). The wound, if any, could then add a flat damage bonus (in case of a minor wound). In case of a major wound, the effect of the minor wound happens, but the target also suffers from some side-effects. This could be open to player-suggestions, but usually covers (combat) impairments such as slower walking speed, aiming penalties etc., continual damage, or just another flat damage bonus.

Conclusion 4. and 5. lead to the idea, that target zones only define on how likely it is to gain a wound. The DC of gaining a wound now is 5 + damage dealt. This could be changed into different DC modifiers for different target zones. So either 10 + damage dealt or 5 + 2 \* (damage dealt) for the torso would work. So no matter where the bullet hits you, it always deals the same damage, unless it creates a wound which would abstract the hitting of some internal organ. Different type of ammo may change the damage (f.e. HP ammo), but this is more easily countered by armour plates or kevlar. AP ammo then would do more or less do the same damage than normal bullets, but are able to penetrate armour.

**Comment by n0la** [comment]
I prefer Oliver's take on it: Bullet damage is fine, people should just be able to take more damage. My proposal:

HP goes from +$HP to -$HP. Below -$HP you are dead. Below 0 you are unconscious, wounded and you slowly lose HP until you reach -$HP or get healed. So you can still take two bullets to the chest (to perhaps -4 HP) but survive if a doctor finds you soon enough. Bullets to vital areas remain as deadly as they are (which is fine imho). I'd just add ballistic helmets (that can protect the brain). The armour plates and ballistic helmets (which will get damaged) serve both a risk factor (do I take one? do I buy one?) and money sink (as they've to be replaced). Wounds just serve to bring you to -$HP and to make you dead, after the bullet has already done its damage. The severity of the wound depend on the damage inflicted of course.

Vital organs hit probability can be reduced. But they are a part of the human body that you can deliberately aim for, so they should not be "crit only". One way would be: roll 2d6 for body zone, if either torso or head, roll another 2d6 and if you roll the same zone again you get a vital organ.

**Comment by johannes-z** [comment]
Something else to consider would be different penalties for movement based on range. Aiming at someone more than 100 metres away while walking towards him shouldn't be as easy as it is right now.

**Comment by n0la** [comment]
I agree. Movement penalties should be higher. Especially if you are the one walking and shooting.

**Comment by n0la** [comment]
Movement penalties have been increased. I think combat is fine as it is. The only potential: more protective gear.
