### ISSUE TITLE
Make Dodging a Melee Combat skill/specialisation

### ISSUE THREAD

**Issue by johannes-z** [ehrpg/books#13]

**Comment by n0la** [comment]
Nope. IMHO Dodging is fine as it is stand-alone.

**Comment by johannes-z** [comment]
Dodging is only needed in melee combat though. You can't dodge a bullet, and for getting into safety from an immediate explosion f.e. requires you to make an athletics/acrobatics check anyway. Since any martial arts also includes defending oneself, dodging could count among them. #9 showed, that there isn't just dodging and blocking, but also deflecting or mitigating, which would also fall under the melee combat skill.

On a site note:  Small arms can be used for any kind of weapon; also medicine can be used for any kind of wound (even for bionics), but specialities like "trauma care" make you better in a certain field - it's no requirement. Meaning, that those skills have a very broad spectrum, whereas dodging is only used for one single purpose.

**Comment by n0la** [comment]
You can dodge a lot of stuff:
- A car that tries to hit you
- Falling or flying debris
- A dog that tries to jump you
- Stuff that is being thrown at you
- Dodge "off" an elevator that will fall into the shaft etc.

Dodging is not melee specific. Acrobatics should only be used if you want to land "nicely" without taking any or much damage. Everyone can dodge (and land on his face), but falling properly should be reserved to people with acrobatic skills.

**Comment by johannes-z** [comment]
Right - did not think of those use cases.
