### ISSUE TITLE
Playtest #1

### ISSUE THREAD

**Issue by johannes-z** [ehrpg/books#2]
- [x] Rules for suppressive fire
- [x] Add skill _Microgravity_
- [x] Add _Throwing_ skill to _Soldier_ background
- [x] Add skill _Breaching_

**Comment by n0la** [comment]
Suppressive fire: https://github.com/ehrpg/books/blob/master/core/chapters/06_combat.tex#L234

**Comment by n0la** [comment]
Microgravity: https://github.com/ehrpg/books/blob/master/core/chapters/04_skills.tex#L164

**Comment by johannes-z** [comment]
Breaching (now called Small Unit Tactics): https://github.com/ehrpg/books/blob/master/core/chapters/04_skills.tex#L247

**Comment by johannes-z** [comment]
Soldier background ajdustment: https://github.com/ehrpg/books/blob/master/core/chapters/05_backgrounds.tex#L209
