### ISSUE TITLE
Playtest #2

### ISSUE THREAD

**Issue by johannes-z** [ehrpg/books#9]
- [x] Swap CON with INT on Notice
- [x] Throwing specialities
- [x] Melee Combat specialities
- [x] Pirate has Smooth Talking at rank 2, although Oratory is only at rank 2.
- [ ] Naming of skills for weapon categories (small, light, heavy). Light weapon may be deceptive
- [x] Dual wielding rules for one hand guns.
- [x] Char sheet skills - total ranks/bonus
- [ ] Contests 

EQUIPMENT:
- [ ] Ballistic shield
- [x] Amount of Magazines per Misc. Slot. Differences between cartridge size.
- [x] Kevlar too cheap compared to low class armour plates.
- [x] RPG, Rocket Launchers, Flame Thrower, 
- [ ] Weapon Accessories (Scopes - effective range, prices, etc.)
- [x] Cheaper (less misc. slots) Chest Carriers.

CHARACTER SHEET
- [ ] Carrying Capacity on charactersheet
- [ ] CCP entry

COMBAT
- [x] Actions in combat
- [x] Too deadly

VESSELS
- [ ] More damage for vessel weaponry (currently way weaker than small arms)

**Comment by n0la** [comment]
Items:
- [x] Add IMI Desert Eagle
- [x] Add .44 Magnum cartridge (for Desert Eagle)

**Comment by n0la** [comment]
"Combat to deadly" discussions will be moved into issue #11.
